### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by turalyf** [allinbit/btc_puzzle#1]
Traceback (most recent call last):
  File "/root/btc/btc.py", line 64, in <module>
    main()
  File "/root/btc/btc.py", line 47, in main
    stop_event = Event()
  File "/usr/lib/python3.9/multiprocessing/context.py", line 93, in Event
    return Event(ctx=self.get_context())
  File "/usr/lib/python3.9/multiprocessing/synchronize.py", line 324, in __init__
    self._cond = ctx.Condition(ctx.Lock())
  File "/usr/lib/python3.9/multiprocessing/context.py", line 68, in Lock
    return Lock(ctx=self.get_context())
  File "/usr/lib/python3.9/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/usr/lib/python3.9/multiprocessing/synchronize.py", line 57, in __init__
    sl = self._semlock = _multiprocessing.SemLock(
FileNotFoundError: [Errno 2] No such file or directory

**Comment by allinbit** [comment]
It looks like you are using linux, try running the script as root user.
